/*
This file is automatically generated.
Fredoka-Medium_28_L4
C Source
*/

#include "Common.h"

#define FONT_HANDLE       (1)
#define FONT_FILE_ADDRESS (RAM_G + 0)
#define FIRST_CHARACTER   (32)

void Load_Font_L4(EVE_HalContext * phost)
{
	Gpu_Hal_LoadImageToMemory(phost, "../../../L4/Fredoka-Medium_28_L4.raw", FONT_FILE_ADDRESS, LOAD);

	Gpu_CoCmd_Dlstart(phost);
	App_WrCoCmd_Buffer(phost, CLEAR(1, 1, 1));
	App_WrCoCmd_Buffer(phost, COLOR_RGB(255, 255, 255));
	Gpu_CoCmd_SetFont2(phost, FONT_HANDLE, FONT_FILE_ADDRESS, FIRST_CHARACTER);
	Gpu_CoCmd_Text(phost, 50, 50, FONT_HANDLE, 0, "\x20\x21\x22\x23\x24");
	App_WrCoCmd_Buffer(phost, DISPLAY());
	Gpu_CoCmd_Swap(phost);
	App_Flush_Co_Buffer(phost);
	Gpu_Hal_WaitCmdfifo_empty(phost);
}

/* end of file */
